### ISSUE TITLE
Licensing question for fork in modpack

### ISSUE THREAD

**Issue by asanetargoss** [TeamDman/Animus#87]
Hey there! I'm the developer of Hardcore Alchemy: Magic With Consequences, a MultiMC-based modpack for Minecraft 1.10.2. As part of Modpack development, I forked one of your mods in accordance with its Creative Commons license as shown on the Curseforge page. Nothing major, I think. I believe I only fixed a crash. Here's the fork:

https://github.com/asanetargoss/Animus

With Curseforge support for Linux seeming likely, I have been exploring the possibility of uploading HcA to Curseforge, but doing so would require the changes I have made to Animus to be on Curseforge in some fashion. With that in mind, I have the following questions:

- What is your preference: Integrating the changes upstream, or a fork with its own Curseforge page?
- If a fork with its own Curseforge page, what is your preferred revenue split?

**Comment by Saereth** [comment]
@TeamDman up to you on this one, I dont mind as long as its a version we're no longer actively supporting

**Comment by asanetargoss** [comment]
Alright, that works for me.

**Comment by asanetargoss** [comment]
Sorry, I misread who the mention was targeted toward. Waiting for further clarification.

**Comment by TeamDman** [comment]
Since it's just a small bugfix I think it makes most sense to just merge to upstream. I'll try and have a fixed build up for you shortly

**Comment by TeamDman** [comment]
I created a PR from your fork, had some issues building the older version so I took the jar from the modpack download.
Usually I would just build on my machine but older forge mods get harder to build every day :/
I decompiled it and did a quick check, the fix is there and there's nothing _sus_ in the jar so should be fine.
https://www.curseforge.com/minecraft/mc-mods/animus/files/3790699
Might take a bit to get reviewed by curseforge
LMK if there's any issues, thanks for the bugfix!

**Comment by asanetargoss** [comment]
Thank you, I appreciate you taking the time to upload it given it's for an older Minecraft version.

I forget exactly what the Animus build process was like. Compiling Blood Magic was a bit awkward if I recall, due to the (since removed I think?) lombok dependency. But it's also possible you might have run into some Maven issues. If I need to make another fix for Animus for whatever reason, it will probably include this:

https://github.com/asanetargoss/ArsMagica2/commit/18e6365dbe455527733e4ea09dbe0c6012774a7d

**Comment by TeamDman** [comment]
I had some success switching to Cursemaven since tehnut's maven has changed
```diff
repositories {
    maven { url "http://dvs1.progwml6.com/files/maven" }
    maven {	url "http://mobiusstrip.eu/maven" }
    maven {	url "http://maven.tehnut.info/" }
+    maven { url "https://cursemaven.com"}
}

dependencies {
    deobfCompile "mezz.jei:jei_${mc_version}:${jei_version}"
-	deobfCompile "info.amerifrance.guideapi:Guide-API:${mc_version}-${guideapi_version}"
-    deobfCompile "com.wayoftime.bloodmagic:BloodMagic:${bloodmagic_version}"
+    deobfCompile "curse.maven:guideapi-228832:2380911"
+    deobfCompile "curse.maven:bloodmagic-224791:2439437"
}
```
but when I built the mod, the lang files weren't working properly, probably a gradle cache issue or something
![image](https://user-images.githubusercontent.com/9356891/168458853-b5fb5f9b-371a-48d4-ab55-16d66278b90b.png)

Hopefully won't have to touch the old version anymore since I never got it working lol
